name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]

# Forces all JavaScript actions in this workflow to execute on Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# Required for OpenID Connect (OIDC) Trusted Publishing
permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 10 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Run xUnit Tests
      run: dotnet test --configuration Release --no-restore

    # - name: Pack Library to NuGet Structure
    #   run: dotnet pack src/FastRng.ThreadSafe.csproj --configuration Release --output ./artifacts
 
    # # nuRequest the token from GitHub and exchange it with NuGet.org
    # - name: NuGet Login
    #   uses: nuget/login@v1
    #   id: oidc_login
    #   with:
    #     user: 'HristoS' # Your exact profile username

    # # Feed the proven NUGET_API_KEY directly into the push script
    # - name: Publish to NuGet
    #   run: |
    #     dotnet nuget push "./artifacts/*.nupkg" \
    #       --source https://api.nuget.org/v3/index.json \
    #       --api-key ${{ steps.oidc_login.outputs.NUGET_API_KEY }} \
    #       --skip-duplicate